#!/bin/sh -eu
# Matrix credentials and temp file for storing previous ham list
HS='https://jkl.hacklab.fi:8448'
ROOM='!BLYeigonHHIgGStfrT%3Airc.snt.utwente.nl'
TOKEN="`cat "$(dirname "$0")/token.txt"`"
KOOLIT_DIR=/PATH/TO/koolit

get_koolit () {
    git cat-file -p "$1:oh-callsigns.tsv" | LC_ALL=C sed -rne 's/^([^\t]*)\tVOIMAS.*/\1/p' | LC_ALL=C sort >"$2"
}

# Operate on koolit repository.
export GIT_DIR="$KOOLIT_DIR/.git"
git fetch

# Check if we have the tag yet
if ! LAST_TIME=`git rev-parse --verify -q tags/koolitutka`; then
    git tag koolitutka origin/master
    echo "Running the first time. Nothing to report. Added 'koolitutka' tag to origin/master."
    exit 0
fi

# Get filtered callsigns of last and this time
tmpnew=`mktemp`
tmpold=`mktemp`
get_koolit koolitutka $tmpold
get_koolit origin/master $tmpnew

# Compare and craft a message
comm -3 --output-delimiter=, "$tmpold" "$tmpnew" | {
    # Populate call list
    while IFS=, read -r cs_dead cs_new; do
	if test "$cs_new"; then
	    item="+$cs_new"
	else
	    item="-$cs_dead"
	fi
	msg="${msg-Traficomista huomenta! }${msg+ }$item"
    done

    if test "${item+ }"; then
	echo -n "$msg" | jq -Rs '{"body":.,"msgtype": "m.notice"}' | curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- "$HS/_matrix/client/r0/rooms/$ROOM/send/m.room.message/`date +%s`?access_token=$TOKEN"
    fi
}

# Update tag
git tag -f koolitutka origin/master

# Clean temp files
rm "$tmpold" "$tmpnew"
