#!/bin/sh -eu
# Matrix credentials and temp file for storing previous ham list
TOKEN="`cat ~/token.txt`"
ROOM='!BLYeigonHHIgGStfrT%3Airc.snt.utwente.nl'
HAMLIST=~/hams.txt

tmpnewraw=`mktemp`
tmpnew=`mktemp`
tmpold=`mktemp`
curl -Ssf 'https://eservices.viestintavirasto.fi/Licensesservices/Forms/AmateurLicenses.aspx' -F __EVENTTARGET= -F ButtonDownload= -o "$tmpnewraw"
grep VOIMAS <"$tmpnewraw" | cut -f 1 | sort >"$tmpnew"
grep VOIMAS <"$HAMLIST" | cut -f 1 | sort >"$tmpold"
comm -3 --output-delimiter=, "$tmpold" "$tmpnew" | {
    # Populate call list
    while IFS=, read -r cs_dead cs_new; do
	if test "$cs_new"; then
	    item="+$cs_new"
	else
	    item="-$cs_dead"
	fi
	msg="${msg-Traficomista huomenta! }${msg+ }$item"
    done

    if test "${item+ }"; then
	echo -n "$msg" | jq -Rs '{"body":.,"msgtype": "m.notice"}' | curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- "https://jkl.hacklab.fi:8448/_matrix/client/r0/rooms/$ROOM/send/m.room.message/`date +%s`?access_token=$TOKEN"
    fi
}

# Replace old list with new and clean temp files
mv "$tmpnewraw" "$HAMLIST"
rm "$tmpold" "$tmpnew"
